#ifndef INCLUDE_TETRIS_CONFIG_H_
#define INCLUDE_TETRIS_CONFIG_H_

#include "driver/gpio.h"

#define GPIO_DISPLAY_SCL GPIO_NUM_8
#define GPIO_DISPLAY_SDA GPIO_NUM_9
#define GPIO_DISPLAY_RES GPIO_NUM_6

#define GPIO_BUTTON_L GPIO_NUM_35
#define GPIO_BUTTON_R GPIO_NUM_36

#define DISPLAY_I2C_ADDR 0x3c

#endif // INCLUDE_TETRIS_CONFIG_H_
