name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches-ignore: []

jobs:
  cmake-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prevent "Processing triggers for man-db" post-install hook
        run: sudo rm /var/lib/man-db/auto-update

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            wget \
            flex \
            bison \
            gperf \
            python3 \
            python3-pip \
            python3-venv \  
            cmake \
            ninja-build \
            ccache \
            libffi-dev \
            libssl-dev \
            dfu-util \
            libusb-1.0-0

      - name: Setup ESP-IDF
        run: |
          git clone --recurisive https://github.com/espressif/esp-idf.git
          cd ./esp-idf
          ./install.sh esp32,esp32s3

      - name: Build project
        run: |
          source ./esp-idf/export.sh
          idf.py app-build
